### ISSUE TITLE
Error: invalid module name: Nim-RunPE

### ISSUE THREAD

**Issue by johnjohnsp1** [S3cur3Th1sSh1t/Nim-RunPE#1]
hello,
trying too compile but sadly return:

nim c -d:release --app:console --cpu:amd64 .\Nim-RunPE.nim
Hint: used config file 'C:\nim-1.6.2\config\nim.cfg' [Conf]
Hint: used config file 'C:\nim-1.6.2\config\config.nims' [Conf]
........................................................
Error: invalid module name: Nim-RunPE

did nimble install ptr_math winim

**Comment by Imanfeng** [comment]
> hello, trying too compile but sadly return:
> 
> nim c -d:release --app:console --cpu:amd64 .\Nim-RunPE.nim Hint: used config file 'C:\nim-1.6.2\config\nim.cfg' [Conf] Hint: used config file 'C:\nim-1.6.2\config\config.nims' [Conf] ........................................................ Error: invalid module name: Nim-RunPE
> 
> did nimble install ptr_math winim

You can try renaming the Nim-RunPE.nim file to e01.nim

**Comment by johnjohnsp1** [comment]
thanks , it worked, seems any named are valid but Nim-RunPE, thanks once more

**Comment by S3cur3Th1sSh1t** [comment]
Also "fixed" with 9c60aac164e1129167b0549f7a4168ea11bae837
