### ISSUE TITLE
Mimi Command Line Arguments

### ISSUE THREAD

**Issue by InitRoot** [S3cur3Th1sSh1t/Nim-RunPE#2]
Did you ever manage to debug the mimi issue? I've compiled my own, but it keeps failing on command line arguments afterwards. I've also seen this injecting into a thread using NIM and mimi, but havn't managed to solve it.

Which version managed to work for you?

**Comment by S3cur3Th1sSh1t** [comment]
Try using Nim Version 1.6.2.

**Comment by S3cur3Th1sSh1t** [comment]
If you still face the issue feel free to re-open.
