### ISSUE TITLE
hi, how i can use this runpe wth 32bit compiled PE (remcos security,warzone control, etc) ? 

### ISSUE THREAD

**Issue by spookycheekybreeky** [S3cur3Th1sSh1t/Nim-RunPE#4]
hi, what i been trying is to replace some ULONGLONG into DWORD statement for getting a working compilation with MinGW 32bit but im getting some weird error on illegal access [log bellow]

(tested with a remcos agent.)
[+] Exe File Prefer Image Base at

Size:
475136
[+] Try to Allocate Memory for New Image Base\n
[+] Mapping Section ...
    [+] Mapping Section :.text
    [+] Mapping Section :.rdata
    [+] Mapping Section :.data
    [+] Mapping Section :.tls
    [+] Mapping Section :.gfids
    [+] Mapping Section :.rsrc
    [+] Mapping Section :.reloc
[+] Fix Import Address Table

    [+] Import DLL: KERNEL32.dll
        [V] API: VirtualFree
        [V] API: VirtualAlloc
        [V] API: LoadLibraryA
        [V] API: GetNativeSystemInfo
        [V] API: HeapAlloc
        [V] API: GetProcAddress
        [V] API: GetProcessHeap
        [V] API: FreeLibrary
        [V] API: IsBadReadPtr
        [V] API: GetCurrentProcess
        [V] API: GetSystemDirectoryA
        [V] API: GlobalAlloc
        [V] API: GlobalLock
        [V] API: GetCurrentProcessId
        [V] API: GetTickCount
        [V] API: GlobalUnlock
        [V] API: LocalAlloc
        [V] API: GetModuleHandleA
        [V] API: GlobalFree
        [V] API: MulDiv
        [V] API: SizeofResource
        [V] API: GetConsoleScreenBufferInfo
        [V] API: SetConsoleTextAttribute
        [V] API: GetStdHandle
        [V] API: RemoveDirectoryW
        [V] API: FindResourceA
        [V] API: OpenProcess
        [V] API: LockResource
        [V] API: LoadResource
        [V] API: LocalFree
        [V] API: GetFileSize
        [V] API: SetConsoleOutputCP
        [V] API: FormatMessageA
        [V] API: AllocConsole
        [V] API: GetModuleFileNameA
        [V] API: lstrcpynA
        [V] API: SetLastError
        [V] API: GetLastError
        [V] API: EnterCriticalSection
        [V] API: LeaveCriticalSection
        [V] API: InitializeCriticalSection
        [V] API: DeleteCriticalSection
        [V] API: HeapSize
        [V] API: WriteConsoleW
        [V] API: SetStdHandle
        [V] API: SetEnvironmentVariableW
        [V] API: SetEnvironmentVariableA
        [V] API: FreeEnvironmentStringsW
        [V] API: GetEnvironmentStringsW
        [V] API: GetCommandLineW
        [V] API: GetCommandLineA
        [V] API: GetOEMCP
        [V] API: IsValidCodePage
        [V] API: FindFirstFileExA
        [V] API: ReadConsoleW
        [V] API: EnumSystemLocalesW
        [V] API: GetUserDefaultLCID
        [V] API: IsValidLocale
        [V] API: GetConsoleMode
        [V] API: GetConsoleCP
        [V] API: FlushFileBuffers
        [V] API: GetFileType
        [V] API: HeapReAlloc
        [V] API: GetACP
        [V] API: GetModuleHandleExW
        [V] API: MoveFileExW
        [V] API: RtlUnwind
        [V] API: RaiseException
        [V] API: VirtualProtect
        [V] API: Process32FirstW
        [V] API: Process32NextW
        [V] API: CreateToolhelp32Snapshot
        [V] API: GetLocaleInfoA
        [V] API: CreateMutexA
        [V] API: ExitProcess
        [V] API: SetFileAttributesW
        [V] API: GetModuleFileNameW
        [V] API: QueryPerformanceFrequency
        [V] API: GetLongPathNameW
        [V] API: ExpandEnvironmentStringsA
        [V] API: FindNextFileA
        [V] API: FindFirstFileA
        [V] API: MoveFileW
        [V] API: WaitForSingleObject
        [V] API: SetFilePointerEx
        [V] API: GetLogicalDriveStringsA
        [V] API: DeleteFileW
        [V] API: DeleteFileA
        [V] API: GetFileAttributesW
        [V] API: CreateFileW
        [V] API: FindClose
        [V] API: lstrlenA
        [V] API: GetDriveTypeA
        [V] API: FindNextFileW
        [V] API: GetFileSizeEx
        [V] API: FindFirstFileW
        [V] API: CreateDirectoryW
        [V] API: CreateProcessA
        [V] API: Sleep
        [V] API: PeekNamedPipe
        [V] API: CreatePipe
        [V] API: TerminateProcess
        [V] API: WriteFile
        [V] API: ReadFile
        [V] API: HeapFree
        [V] API: HeapCreate
        [V] API: CreateEventA
        [V] API: GetLocalTime
        [V] API: CreateThread
        [V] API: CloseHandle
        [V] API: SetEvent
        [V] API: CreateEventW
        [V] API: QueryPerformanceCounter
        [V] API: LoadLibraryExW
        [V] API: GetCPInfo
        [V] API: GetStringTypeW
        [V] API: GetLocaleInfoW
        [V] API: LCMapStringW
        [V] API: CompareStringW
        [V] API: TlsFree
        [V] API: TlsSetValue
        [V] API: TlsGetValue
        [V] API: TlsAlloc
        [V] API: InitializeCriticalSectionAndSpinCount
        [V] API: MultiByteToWideChar
        [V] API: DecodePointer
        [V] API: EncodePointer
        [V] API: WideCharToMultiByte
        [V] API: InitializeSListHead
        [V] API: GetSystemTimeAsFileTime
        [V] API: GetCurrentThreadId
        [V] API: GetStartupInfoW
        [V] API: SetUnhandledExceptionFilter
        [V] API: UnhandledExceptionFilter
        [V] API: IsDebuggerPresent
        [V] API: IsProcessorFeaturePresent
        [V] API: GetModuleHandleW
        [V] API: WaitForSingleObjectEx
        [V] API: ResetEvent
        [V] API: SetEndOfFile
    [+] Import DLL: USER32.dll
        [V] API: EnumWindows
        [V] API: TranslateMessage
        [V] API: DispatchMessageA
        [V] API: GetMessageA
        [V] API: GetWindowTextW
        [V] API: SetForegroundWindow
        [V] API: SetClipboardData
        [V] API: GetClipboardData
        [V] API: MessageBoxW
        [V] API: IsWindowVisible
        [V] API: CloseWindow
        [V] API: GetWindowThreadProcessId
        [V] API: SendInput
        [V] API: EnumDisplaySettingsW
        [V] API: mouse_event
        [V] API: DrawIcon
        [V] API: GetSystemMetrics
        [V] API: GetIconInfo
        [V] API: SystemParametersInfoW
        [V] API: GetForegroundWindow
        [V] API: GetCursorPos
        [V] API: RegisterClassExA
        [V] API: AppendMenuA
        [V] API: CreateWindowExA
        [V] API: DefWindowProcA
        [V] API: TrackPopupMenu
        [V] API: CreatePopupMenu
        [V] API: ShowWindow
        [V] API: OpenClipboard
        [V] API: SetWindowTextW
        [V] API: ExitWindowsEx
        [V] API: EmptyClipboard
        [V] API: CloseClipboard
    [+] Import DLL: GDI32.dll
        [V] API: CreateCompatibleBitmap
        [V] API: SelectObject
        [V] API: CreateCompatibleDC
        [V] API: StretchBlt
        [V] API: GetDIBits
        [V] API: DeleteDC
        [V] API: DeleteObject
        [V] API: CreateDCA
        [V] API: GetObjectA
    [+] Import DLL: ADVAPI32.dll
        [V] API: RegCreateKeyW
        [V] API: CryptAcquireContextA
        [V] API: CryptGenRandom
        [V] API: CryptReleaseContext
        [V] API: GetUserNameW
        [V] API: RegEnumKeyExA
        [V] API: QueryServiceStatus
        [V] API: CloseServiceHandle
        [V] API: OpenSCManagerW
        [V] API: OpenSCManagerA
        [V] API: ControlService
        [V] API: StartServiceW
        [V] API: QueryServiceConfigW
        [V] API: ChangeServiceConfigW
        [V] API: OpenServiceW
        [V] API: EnumServicesStatusW
        [V] API: AdjustTokenPrivileges
        [V] API: LookupPrivilegeValueA
        [V] API: OpenProcessToken
        [V] API: RegCreateKeyA
        [V] API: RegCloseKey
        [V] API: RegQueryInfoKeyW
        [V] API: RegQueryValueExA
        [V] API: RegCreateKeyExW
        [V] API: RegEnumKeyExW
        [V] API: RegSetValueExW
        [V] API: RegSetValueExA
        [V] API: RegOpenKeyExA
        [V] API: RegOpenKeyExW
        [V] API: RegDeleteValueW
        [V] API: RegEnumValueW
        [V] API: RegQueryValueExW
        [V] API: RegDeleteKeyA
    [+] Import DLL: SHELL32.dll
        [V] API: ShellExecuteExA
        [V] API: Shell_NotifyIconA
        [V] API: ExtractIconA
        [V] API: ShellExecuteW
    [+] Import DLL: SHLWAPI.dll
        [V] API: StrToIntA
        [V] API: PathFileExistsA
        [V] API: PathFileExistsW
    [+] Import DLL: WINMM.dll
        [V] API: PlaySoundW
        [V] API: mciSendStringA
        [V] API: mciSendStringW
    [+] Import DLL: WS2_32.dll
        [V] API ord: 4
        [V] API ord: 23
        [V] API ord: 19
        [V] API ord: 115
        [V] API ord: 16
        [V] API ord: 9
        [V] API ord: 8
        [V] API ord: 55
        [V] API ord: 12
        [V] API ord: 15
        [V] API ord: 56
        [V] API ord: 51
        [V] API ord: 111
        [V] API ord: 112
        [V] API ord: 11
        [V] API ord: 3
        [V] API ord: 52
    [+] Import DLL: urlmon.dll
        [V] API: URLOpenBlockingStreamW
        [V] API: URLDownloadToFileW
    [+] Import DLL: gdiplus.dll
        [V] API: GdiplusStartup
        [V] API: GdipDisposeImage
        [V] API: GdipLoadImageFromStream
        [V] API: GdipSaveImageToStream
        [V] API: GdipGetImageEncodersSize
        [V] API: GdipFree
        [V] API: GdipGetImageEncoders
        [V] API: GdipCloneImage
        [V] API: GdipAlloc
    [+] Import DLL: WININET.dll
        [V] API: InternetOpenW
        [V] API: InternetCloseHandle
        [V] API: InternetReadFile
        [V] API: InternetOpenUrlW
[+] TLS Directory found
    [+] TLS Callback: ptr 0044C52C --> 877676865
Traceback (most recent call last)
C:\Users\zingstrok\Desktop\Nim-RunPE-main\test.nim(278) test
C:\Users\zingstrok\Desktop\Nim-RunPE-main\test.nim(229) ExecTLSCallbacks
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by S3cur3Th1sSh1t** [comment]
I’m not 100% sure but you could try removing the tls callback handling as this fails here.

**Comment by spookycheekybreeky** [comment]
Yes, that what i ended up doing and that work without any problem, thank for the code anyway!
